services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - "mongo_data:/data/db" 

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types" 
    depends_on:
      - catalogdb
    ports:
      - "8000:80" # 8000 is port from launchSetting.json and # 80 is port from Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro